//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordPress.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordPress.Localization.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordPress.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to above text.
        /// </summary>
        internal static string ControlText_AboveText {
            get {
                return ResourceManager.GetString("ControlText_AboveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account details.
        /// </summary>
        internal static string ControlText_AccountDetails {
            get {
                return ResourceManager.GetString("ControlText_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new.
        /// </summary>
        internal static string ControlText_Add {
            get {
                return ResourceManager.GetString("ControlText_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a page.
        /// </summary>
        internal static string ControlText_AddAPage {
            get {
                return ResourceManager.GetString("ControlText_AddAPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add blog.
        /// </summary>
        internal static string ControlText_AddBlog {
            get {
                return ResourceManager.GetString("ControlText_AddBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add self-hosted WordPress blog.
        /// </summary>
        internal static string ControlText_AddExistingSite {
            get {
                return ResourceManager.GetString("ControlText_AddExistingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add blog hosted at WordPress.com.
        /// </summary>
        internal static string ControlText_AddExistingWPBlog {
            get {
                return ResourceManager.GetString("ControlText_AddExistingWPBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string ControlText_AddMedia {
            get {
                return ResourceManager.GetString("ControlText_AddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a tag line to new posts.
        /// </summary>
        internal static string ControlText_AddTaglineToNewPosts {
            get {
                return ResourceManager.GetString("ControlText_AddTaglineToNewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align thumbnail to center.
        /// </summary>
        internal static string ControlText_AlignThumbnailToCenter {
            get {
                return ResourceManager.GetString("ControlText_AlignThumbnailToCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve.
        /// </summary>
        internal static string ControlText_Approve {
            get {
                return ResourceManager.GetString("ControlText_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below text.
        /// </summary>
        internal static string ControlText_BelowText {
            get {
                return ResourceManager.GetString("ControlText_BelowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blink notification light.
        /// </summary>
        internal static string ControlText_BlinkNotificationLight {
            get {
                return ResourceManager.GetString("ControlText_BlinkNotificationLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b-quote.
        /// </summary>
        internal static string ControlText_BlockQuote {
            get {
                return ResourceManager.GetString("ControlText_BlockQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog settings.
        /// </summary>
        internal static string ControlText_BlogSettings {
            get {
                return ResourceManager.GetString("ControlText_BlogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog url.
        /// </summary>
        internal static string ControlText_BlogUrl {
            get {
                return ResourceManager.GetString("ControlText_BlogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string ControlText_Bold {
            get {
                return ResourceManager.GetString("ControlText_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string ControlText_Cancel {
            get {
                return ResourceManager.GetString("ControlText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category description (optional).
        /// </summary>
        internal static string ControlText_CategoryDescription {
            get {
                return ResourceManager.GetString("ControlText_CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category name.
        /// </summary>
        internal static string ControlText_CategoryName {
            get {
                return ResourceManager.GetString("ControlText_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category parent (optional).
        /// </summary>
        internal static string ControlText_CategoryParent {
            get {
                return ResourceManager.GetString("ControlText_CategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category slug (optional).
        /// </summary>
        internal static string ControlText_CategorySlug {
            get {
                return ResourceManager.GetString("ControlText_CategorySlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment notifications.
        /// </summary>
        internal static string ControlText_CommentNotifications {
            get {
                return ResourceManager.GetString("ControlText_CommentNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted from WordPress for WP7.
        /// </summary>
        internal static string ControlText_DefaultTagLine {
            get {
                return ResourceManager.GetString("ControlText_DefaultTagLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string ControlText_Delete {
            get {
                return ResourceManager.GetString("ControlText_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string ControlText_Edit {
            get {
                return ResourceManager.GetString("ControlText_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geotag posts.
        /// </summary>
        internal static string ControlText_GeoTagPosts {
            get {
                return ResourceManager.GetString("ControlText_GeoTagPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a free blog at WordPress.com.
        /// </summary>
        internal static string ControlText_GetBlog {
            get {
                return ResourceManager.GetString("ControlText_GetBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string ControlText_Italic {
            get {
                return ResourceManager.GetString("ControlText_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        internal static string ControlText_Link {
            get {
                return ResourceManager.GetString("ControlText_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string ControlText_Location {
            get {
                return ResourceManager.GetString("ControlText_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum thumbnail pixel width.
        /// </summary>
        internal static string ControlText_MaximumThumbnailPixelWidth {
            get {
                return ResourceManager.GetString("ControlText_MaximumThumbnailPixelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media.
        /// </summary>
        internal static string ControlText_Media {
            get {
                return ResourceManager.GetString("ControlText_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate comments.
        /// </summary>
        internal static string ControlText_ModerateComments {
            get {
                return ResourceManager.GetString("ControlText_ModerateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t yet have a blog?.
        /// </summary>
        internal static string ControlText_NeedBlog {
            get {
                return ResourceManager.GetString("ControlText_NeedBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [none].
        /// </summary>
        internal static string ControlText_None {
            get {
                return ResourceManager.GetString("ControlText_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page content.
        /// </summary>
        internal static string ControlText_PageContent {
            get {
                return ResourceManager.GetString("ControlText_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string ControlText_Password {
            get {
                return ResourceManager.GetString("ControlText_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place image.
        /// </summary>
        internal static string ControlText_PlaceImage {
            get {
                return ResourceManager.GetString("ControlText_PlaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play notification sound.
        /// </summary>
        internal static string ControlText_PlayNotificationSound {
            get {
                return ResourceManager.GetString("ControlText_PlayNotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post content.
        /// </summary>
        internal static string ControlText_PostContent {
            get {
                return ResourceManager.GetString("ControlText_PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post signature.
        /// </summary>
        internal static string ControlText_PostSignature {
            get {
                return ResourceManager.GetString("ControlText_PostSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferences.
        /// </summary>
        internal static string ControlText_Preferences {
            get {
                return ResourceManager.GetString("ControlText_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish.
        /// </summary>
        internal static string ControlText_Publish {
            get {
                return ResourceManager.GetString("ControlText_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        internal static string ControlText_Refresh {
            get {
                return ResourceManager.GetString("ControlText_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        internal static string ControlText_Reply {
            get {
                return ResourceManager.GetString("ControlText_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string ControlText_Save {
            get {
                return ResourceManager.GetString("ControlText_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select categories.
        /// </summary>
        internal static string ControlText_SelectCategories {
            get {
                return ResourceManager.GetString("ControlText_SelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected categories.
        /// </summary>
        internal static string ControlText_SelectedCategories {
            get {
                return ResourceManager.GetString("ControlText_SelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spam.
        /// </summary>
        internal static string ControlText_Spam {
            get {
                return ResourceManager.GetString("ControlText_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start blogging from Windows Phone 7 in seconds.
        /// </summary>
        internal static string ControlText_StartBloggingInSeconds {
            get {
                return ResourceManager.GetString("ControlText_StartBloggingInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new blog at WordPress.com.
        /// </summary>
        internal static string ControlText_StartNewBlog {
            get {
                return ResourceManager.GetString("ControlText_StartNewBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string ControlText_Status {
            get {
                return ResourceManager.GetString("ControlText_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC.
        /// </summary>
        internal static string ControlText_StrikeThrough {
            get {
                return ResourceManager.GetString("ControlText_StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags &amp; categories.
        /// </summary>
        internal static string ControlText_TagsAndCategories {
            get {
                return ResourceManager.GetString("ControlText_TagsAndCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unapprove.
        /// </summary>
        internal static string ControlText_Unapprove {
            get {
                return ResourceManager.GetString("ControlText_Unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string ControlText_Underline {
            get {
                return ResourceManager.GetString("ControlText_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update interval.
        /// </summary>
        internal static string ControlText_UpdateInterval {
            get {
                return ResourceManager.GetString("ControlText_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload and link to full image.
        /// </summary>
        internal static string ControlText_UploadAndLinkToFullImage {
            get {
                return ResourceManager.GetString("ControlText_UploadAndLinkToFullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload changes.
        /// </summary>
        internal static string ControlText_UploadChanges {
            get {
                return ResourceManager.GetString("ControlText_UploadChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        internal static string ControlText_Username {
            get {
                return ResourceManager.GetString("ControlText_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrate.
        /// </summary>
        internal static string ControlText_Vibrate {
            get {
                return ResourceManager.GetString("ControlText_Vibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write.
        /// </summary>
        internal static string ControlText_Write {
            get {
                return ResourceManager.GetString("ControlText_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approving comment....
        /// </summary>
        internal static string Messages_ApprovingComment {
            get {
                return ResourceManager.GetString("Messages_ApprovingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approving comments....
        /// </summary>
        internal static string Messages_ApprovingComments {
            get {
                return ResourceManager.GetString("Messages_ApprovingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating new category....
        /// </summary>
        internal static string Messages_CreatingNewCategory {
            get {
                return ResourceManager.GetString("Messages_CreatingNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting comment....
        /// </summary>
        internal static string Messages_DeletingComment {
            get {
                return ResourceManager.GetString("Messages_DeletingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting comments....
        /// </summary>
        internal static string Messages_DeletingComments {
            get {
                return ResourceManager.GetString("Messages_DeletingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting page....
        /// </summary>
        internal static string Messages_DeletingPage {
            get {
                return ResourceManager.GetString("Messages_DeletingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting post....
        /// </summary>
        internal static string Messages_DeletingPost {
            get {
                return ResourceManager.GetString("Messages_DeletingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in....
        /// </summary>
        internal static string Messages_LoggingIn {
            get {
                return ResourceManager.GetString("Messages_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marking comment as spam....
        /// </summary>
        internal static string Messages_MarkingAsSpam {
            get {
                return ResourceManager.GetString("Messages_MarkingAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marking comments as spam....
        /// </summary>
        internal static string Messages_MarkingCommentsAsSpam {
            get {
                return ResourceManager.GetString("Messages_MarkingCommentsAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reply..
        /// </summary>
        internal static string Messages_MissingReply {
            get {
                return ResourceManager.GetString("Messages_MissingReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replying to comment....
        /// </summary>
        internal static string Messages_ReplyingToComment {
            get {
                return ResourceManager.GetString("Messages_ReplyingToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving categories....
        /// </summary>
        internal static string Messages_RetrievingCategories {
            get {
                return ResourceManager.GetString("Messages_RetrievingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving comments....
        /// </summary>
        internal static string Messages_RetrievingComments {
            get {
                return ResourceManager.GetString("Messages_RetrievingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving everything....
        /// </summary>
        internal static string Messages_RetrievingEverything {
            get {
                return ResourceManager.GetString("Messages_RetrievingEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving page....
        /// </summary>
        internal static string Messages_RetrievingPage {
            get {
                return ResourceManager.GetString("Messages_RetrievingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving pages....
        /// </summary>
        internal static string Messages_RetrievingPages {
            get {
                return ResourceManager.GetString("Messages_RetrievingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving post....
        /// </summary>
        internal static string Messages_RetrievingPost {
            get {
                return ResourceManager.GetString("Messages_RetrievingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving posts....
        /// </summary>
        internal static string Messages_RetrievingPosts {
            get {
                return ResourceManager.GetString("Messages_RetrievingPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unapproving comment....
        /// </summary>
        internal static string Messages_UnapprovingComment {
            get {
                return ResourceManager.GetString("Messages_UnapprovingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unapproving comments....
        /// </summary>
        internal static string Messages_UnapprovingComments {
            get {
                return ResourceManager.GetString("Messages_UnapprovingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading changes....
        /// </summary>
        internal static string Messages_UploadingChanges {
            get {
                return ResourceManager.GetString("Messages_UploadingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete page.
        /// </summary>
        internal static string Options_PageActions_DeletePage {
            get {
                return ResourceManager.GetString("Options_PageActions_DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit page.
        /// </summary>
        internal static string Options_PageActions_EditPage {
            get {
                return ResourceManager.GetString("Options_PageActions_EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view comments.
        /// </summary>
        internal static string Options_PageActions_ViewComments {
            get {
                return ResourceManager.GetString("Options_PageActions_ViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view page.
        /// </summary>
        internal static string Options_PageActions_ViewPage {
            get {
                return ResourceManager.GetString("Options_PageActions_ViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete post.
        /// </summary>
        internal static string Options_PostActions_DeletePost {
            get {
                return ResourceManager.GetString("Options_PostActions_DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit post.
        /// </summary>
        internal static string Options_PostActions_EditPost {
            get {
                return ResourceManager.GetString("Options_PostActions_EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view comments.
        /// </summary>
        internal static string Options_PostActions_ViewComments {
            get {
                return ResourceManager.GetString("Options_PostActions_ViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view post.
        /// </summary>
        internal static string Options_PostActions_ViewPost {
            get {
                return ResourceManager.GetString("Options_PostActions_ViewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string Options_RefreshEntity_Comments {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everything.
        /// </summary>
        internal static string Options_RefreshEntity_Everything {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        internal static string Options_RefreshEntity_Pages {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posts.
        /// </summary>
        internal static string Options_RefreshEntity_Posts {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Actions.
        /// </summary>
        internal static string Prompt_PageActions {
            get {
                return ResourceManager.GetString("Prompt_PageActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Actions.
        /// </summary>
        internal static string Prompt_PostActions {
            get {
                return ResourceManager.GetString("Prompt_PostActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a thumbnail size..
        /// </summary>
        internal static string Prompt_SelectThumbnailSize {
            get {
                return ResourceManager.GetString("Prompt_SelectThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a category name..
        /// </summary>
        internal static string Prompts_MissingCategoryName {
            get {
                return ResourceManager.GetString("Prompts_MissingCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string Prompts_MissingPassword {
            get {
                return ResourceManager.GetString("Prompts_MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a url..
        /// </summary>
        internal static string Prompts_MissingUrl {
            get {
                return ResourceManager.GetString("Prompts_MissingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name..
        /// </summary>
        internal static string Prompts_MissingUserName {
            get {
                return ResourceManager.GetString("Prompts_MissingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to refresh?.
        /// </summary>
        internal static string Prompts_RefreshEntity {
            get {
                return ResourceManager.GetString("Prompts_RefreshEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category..
        /// </summary>
        internal static string Prompts_SelectCategory {
            get {
                return ResourceManager.GetString("Prompts_SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        internal static string Title_Actions {
            get {
                return ResourceManager.GetString("Title_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add account.
        /// </summary>
        internal static string Title_AddAccount {
            get {
                return ResourceManager.GetString("Title_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new category.
        /// </summary>
        internal static string Title_AddNewCategory {
            get {
                return ResourceManager.GetString("Title_AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string Title_All {
            get {
                return ResourceManager.GetString("Title_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVE.
        /// </summary>
        internal static string Title_Approve {
            get {
                return ResourceManager.GetString("Title_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blogs.
        /// </summary>
        internal static string Title_Blogs {
            get {
                return ResourceManager.GetString("Title_Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string Title_Comments {
            get {
                return ResourceManager.GetString("Title_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit page.
        /// </summary>
        internal static string Title_EditPage {
            get {
                return ResourceManager.GetString("Title_EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit post.
        /// </summary>
        internal static string Title_EditPost {
            get {
                return ResourceManager.GetString("Title_EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate comment.
        /// </summary>
        internal static string Title_ModerateComment {
            get {
                return ResourceManager.GetString("Title_ModerateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate comments.
        /// </summary>
        internal static string Title_ModerateComments {
            get {
                return ResourceManager.GetString("Title_ModerateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        internal static string Title_Pages {
            get {
                return ResourceManager.GetString("Title_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posts.
        /// </summary>
        internal static string Title_Posts {
            get {
                return ResourceManager.GetString("Title_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferences.
        /// </summary>
        internal static string Title_Preferences {
            get {
                return ResourceManager.GetString("Title_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select categories.
        /// </summary>
        internal static string Title_SelectCategories {
            get {
                return ResourceManager.GetString("Title_SelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAM.
        /// </summary>
        internal static string Title_Spam {
            get {
                return ResourceManager.GetString("Title_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stats.
        /// </summary>
        internal static string Title_Stats {
            get {
                return ResourceManager.GetString("Title_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNAPPROVE.
        /// </summary>
        internal static string Title_Unapprove {
            get {
                return ResourceManager.GetString("Title_Unapprove", resourceCulture);
            }
        }
    }
}
