//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordPress.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordPress.Localization.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordPress.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to above text.
        /// </summary>
        internal static string ControlText_AboveText {
            get {
                return ResourceManager.GetString("ControlText_AboveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string ControlText_Accept {
            get {
                return ResourceManager.GetString("ControlText_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account details.
        /// </summary>
        internal static string ControlText_AccountDetails {
            get {
                return ResourceManager.GetString("ControlText_AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new.
        /// </summary>
        internal static string ControlText_Add {
            get {
                return ResourceManager.GetString("ControlText_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add all.
        /// </summary>
        internal static string ControlText_AddAll {
            get {
                return ResourceManager.GetString("ControlText_AddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a page.
        /// </summary>
        internal static string ControlText_AddAPage {
            get {
                return ResourceManager.GetString("ControlText_AddAPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add blog.
        /// </summary>
        internal static string ControlText_AddBlog {
            get {
                return ResourceManager.GetString("ControlText_AddBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add self-hosted WordPress blog.
        /// </summary>
        internal static string ControlText_AddExistingSite {
            get {
                return ResourceManager.GetString("ControlText_AddExistingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add blog hosted at WordPress.com.
        /// </summary>
        internal static string ControlText_AddExistingWPBlog {
            get {
                return ResourceManager.GetString("ControlText_AddExistingWPBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string ControlText_AddMedia {
            get {
                return ResourceManager.GetString("ControlText_AddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add selected.
        /// </summary>
        internal static string ControlText_AddSelected {
            get {
                return ResourceManager.GetString("ControlText_AddSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a tag line to new posts.
        /// </summary>
        internal static string ControlText_AddTaglineToNewPosts {
            get {
                return ResourceManager.GetString("ControlText_AddTaglineToNewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to align thumbnail to center.
        /// </summary>
        internal static string ControlText_AlignThumbnailToCenter {
            get {
                return ResourceManager.GetString("ControlText_AlignThumbnailToCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api key.
        /// </summary>
        internal static string ControlText_Apikey {
            get {
                return ResourceManager.GetString("ControlText_Apikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve.
        /// </summary>
        internal static string ControlText_Approve {
            get {
                return ResourceManager.GetString("ControlText_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        internal static string ControlText_Back {
            get {
                return ResourceManager.GetString("ControlText_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below text.
        /// </summary>
        internal static string ControlText_BelowText {
            get {
                return ResourceManager.GetString("ControlText_BelowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blink notification light.
        /// </summary>
        internal static string ControlText_BlinkNotificationLight {
            get {
                return ResourceManager.GetString("ControlText_BlinkNotificationLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b-quote.
        /// </summary>
        internal static string ControlText_BlockQuote {
            get {
                return ResourceManager.GetString("ControlText_BlockQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog settings.
        /// </summary>
        internal static string ControlText_BlogSettings {
            get {
                return ResourceManager.GetString("ControlText_BlogSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog url.
        /// </summary>
        internal static string ControlText_BlogUrl {
            get {
                return ResourceManager.GetString("ControlText_BlogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string ControlText_Bold {
            get {
                return ResourceManager.GetString("ControlText_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string ControlText_Cancel {
            get {
                return ResourceManager.GetString("ControlText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category description (optional).
        /// </summary>
        internal static string ControlText_CategoryDescription {
            get {
                return ResourceManager.GetString("ControlText_CategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category name.
        /// </summary>
        internal static string ControlText_CategoryName {
            get {
                return ResourceManager.GetString("ControlText_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category parent (optional).
        /// </summary>
        internal static string ControlText_CategoryParent {
            get {
                return ResourceManager.GetString("ControlText_CategoryParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category slug (optional).
        /// </summary>
        internal static string ControlText_CategorySlug {
            get {
                return ResourceManager.GetString("ControlText_CategorySlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string ControlText_Clear {
            get {
                return ResourceManager.GetString("ControlText_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicks.
        /// </summary>
        internal static string ControlText_Clicks {
            get {
                return ResourceManager.GetString("ControlText_Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment notifications.
        /// </summary>
        internal static string ControlText_CommentNotifications {
            get {
                return ResourceManager.GetString("ControlText_CommentNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        internal static string ControlText_Content {
            get {
                return ResourceManager.GetString("ControlText_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Error Message.
        /// </summary>
        internal static string ControlText_CopyErrorMessage {
            get {
                return ResourceManager.GetString("ControlText_CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ControlText_Date {
            get {
                return ResourceManager.GetString("ControlText_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string ControlText_Decline {
            get {
                return ResourceManager.GetString("ControlText_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted from WordPress for Windows Phone.
        /// </summary>
        internal static string ControlText_DefaultTagLine {
            get {
                return ResourceManager.GetString("ControlText_DefaultTagLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string ControlText_Delete {
            get {
                return ResourceManager.GetString("ControlText_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete blog.
        /// </summary>
        internal static string ControlText_DeleteBlog {
            get {
                return ResourceManager.GetString("ControlText_DeleteBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string ControlText_Draft {
            get {
                return ResourceManager.GetString("ControlText_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string ControlText_Edit {
            get {
                return ResourceManager.GetString("ControlText_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [optional] enter the text that should appear for the link..
        /// </summary>
        internal static string ControlText_EnterLinkText {
            get {
                return ResourceManager.GetString("ControlText_EnterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the url for the link you&apos;d like to insert..
        /// </summary>
        internal static string ControlText_EnterURL {
            get {
                return ResourceManager.GetString("ControlText_EnterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreement.
        /// </summary>
        internal static string ControlText_EULA {
            get {
                return ResourceManager.GetString("ControlText_EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit FAQ.
        /// </summary>
        internal static string ControlText_FAQ {
            get {
                return ResourceManager.GetString("ControlText_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Forums.
        /// </summary>
        internal static string ControlText_Forums {
            get {
                return ResourceManager.GetString("ControlText_Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geotag posts.
        /// </summary>
        internal static string ControlText_GeoTagPosts {
            get {
                return ResourceManager.GetString("ControlText_GeoTagPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a free blog at WordPress.com.
        /// </summary>
        internal static string ControlText_GetBlog {
            get {
                return ResourceManager.GetString("ControlText_GetBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert link.
        /// </summary>
        internal static string ControlText_InsertLink {
            get {
                return ResourceManager.GetString("ControlText_InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string ControlText_Italic {
            get {
                return ResourceManager.GetString("ControlText_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        internal static string ControlText_Link {
            get {
                return ResourceManager.GetString("ControlText_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading content.
        /// </summary>
        internal static string ControlText_LoadingContent {
            get {
                return ResourceManager.GetString("ControlText_LoadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string ControlText_Location {
            get {
                return ResourceManager.GetString("ControlText_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media.
        /// </summary>
        internal static string ControlText_Media {
            get {
                return ResourceManager.GetString("ControlText_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate comments.
        /// </summary>
        internal static string ControlText_ModerateComments {
            get {
                return ResourceManager.GetString("ControlText_ModerateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t yet have a blog?.
        /// </summary>
        internal static string ControlText_NeedBlog {
            get {
                return ResourceManager.GetString("ControlText_NeedBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [none].
        /// </summary>
        internal static string ControlText_None {
            get {
                return ResourceManager.GetString("ControlText_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Title for this Item.
        /// </summary>
        internal static string ControlText_NoTitle {
            get {
                return ResourceManager.GetString("ControlText_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original size.
        /// </summary>
        internal static string ControlText_OriginalSize {
            get {
                return ResourceManager.GetString("ControlText_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OG.
        /// </summary>
        internal static string ControlText_OriginalSizeAbbr {
            get {
                return ResourceManager.GetString("ControlText_OriginalSizeAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page content.
        /// </summary>
        internal static string ControlText_PageContent {
            get {
                return ResourceManager.GetString("ControlText_PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string ControlText_Password {
            get {
                return ResourceManager.GetString("ControlText_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Review.
        /// </summary>
        internal static string ControlText_PendingReview {
            get {
                return ResourceManager.GetString("ControlText_PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        internal static string ControlText_Pin {
            get {
                return ResourceManager.GetString("ControlText_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place image.
        /// </summary>
        internal static string ControlText_PlaceImage {
            get {
                return ResourceManager.GetString("ControlText_PlaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play notification sound.
        /// </summary>
        internal static string ControlText_PlayNotificationSound {
            get {
                return ResourceManager.GetString("ControlText_PlayNotificationSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post content.
        /// </summary>
        internal static string ControlText_PostContent {
            get {
                return ResourceManager.GetString("ControlText_PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post signature.
        /// </summary>
        internal static string ControlText_PostSignature {
            get {
                return ResourceManager.GetString("ControlText_PostSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ControlText_PostStatus {
            get {
                return ResourceManager.GetString("ControlText_PostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Title.
        /// </summary>
        internal static string ControlText_PostTitle {
            get {
                return ResourceManager.GetString("ControlText_PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferences.
        /// </summary>
        internal static string ControlText_Preferences {
            get {
                return ResourceManager.GetString("ControlText_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Bandwidth Usage.
        /// </summary>
        internal static string ControlText_PreserveBandwidth {
            get {
                return ResourceManager.GetString("ControlText_PreserveBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish.
        /// </summary>
        internal static string ControlText_Publish {
            get {
                return ResourceManager.GetString("ControlText_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publish date.
        /// </summary>
        internal static string ControlText_PublishDate {
            get {
                return ResourceManager.GetString("ControlText_PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull down to refresh.
        /// </summary>
        internal static string ControlText_PullDownToRefresh {
            get {
                return ResourceManager.GetString("ControlText_PullDownToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader.
        /// </summary>
        internal static string ControlText_Reader {
            get {
                return ResourceManager.GetString("ControlText_Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrers.
        /// </summary>
        internal static string ControlText_Referrers {
            get {
                return ResourceManager.GetString("ControlText_Referrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        internal static string ControlText_Refresh {
            get {
                return ResourceManager.GetString("ControlText_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release to refresh.
        /// </summary>
        internal static string ControlText_ReleaseToRefresh {
            get {
                return ResourceManager.GetString("ControlText_ReleaseToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ControlText_Remove {
            get {
                return ResourceManager.GetString("ControlText_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        internal static string ControlText_Reply {
            get {
                return ResourceManager.GetString("ControlText_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string ControlText_Save {
            get {
                return ResourceManager.GetString("ControlText_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save draft.
        /// </summary>
        internal static string ControlText_SaveDraft {
            get {
                return ResourceManager.GetString("ControlText_SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string ControlText_Scheduled {
            get {
                return ResourceManager.GetString("ControlText_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Terms.
        /// </summary>
        internal static string ControlText_SearchTerms {
            get {
                return ResourceManager.GetString("ControlText_SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the blog or blogs you&apos;d like to import..
        /// </summary>
        internal static string ControlText_SelectBlogs {
            get {
                return ResourceManager.GetString("ControlText_SelectBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select categories.
        /// </summary>
        internal static string ControlText_SelectCategories {
            get {
                return ResourceManager.GetString("ControlText_SelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected categories.
        /// </summary>
        internal static string ControlText_SelectedCategories {
            get {
                return ResourceManager.GetString("ControlText_SelectedCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spam.
        /// </summary>
        internal static string ControlText_Spam {
            get {
                return ResourceManager.GetString("ControlText_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start blogging from Windows Phone 7 in seconds.
        /// </summary>
        internal static string ControlText_StartBloggingInSeconds {
            get {
                return ResourceManager.GetString("ControlText_StartBloggingInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new blog at WordPress.com.
        /// </summary>
        internal static string ControlText_StartNewBlog {
            get {
                return ResourceManager.GetString("ControlText_StartNewBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string ControlText_Status {
            get {
                return ResourceManager.GetString("ControlText_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC.
        /// </summary>
        internal static string ControlText_StrikeThrough {
            get {
                return ResourceManager.GetString("ControlText_StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags &amp; categories.
        /// </summary>
        internal static string ControlText_TagsAndCategories {
            get {
                return ResourceManager.GetString("ControlText_TagsAndCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string ControlText_Title {
            get {
                return ResourceManager.GetString("ControlText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unapprove.
        /// </summary>
        internal static string ControlText_Unapprove {
            get {
                return ResourceManager.GetString("ControlText_Unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string ControlText_Underline {
            get {
                return ResourceManager.GetString("ControlText_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpin.
        /// </summary>
        internal static string ControlText_Unpin {
            get {
                return ResourceManager.GetString("ControlText_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update interval.
        /// </summary>
        internal static string ControlText_UpdateInterval {
            get {
                return ResourceManager.GetString("ControlText_UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create link to full image.
        /// </summary>
        internal static string ControlText_UploadAndLinkToFullImage {
            get {
                return ResourceManager.GetString("ControlText_UploadAndLinkToFullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload changes.
        /// </summary>
        internal static string ControlText_UploadChanges {
            get {
                return ResourceManager.GetString("ControlText_UploadChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string ControlText_Username {
            get {
                return ResourceManager.GetString("ControlText_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vibrate.
        /// </summary>
        internal static string ControlText_Vibrate {
            get {
                return ResourceManager.GetString("ControlText_Vibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ControlText_Views {
            get {
                return ResourceManager.GetString("ControlText_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view stats.
        /// </summary>
        internal static string ControlText_ViewStats {
            get {
                return ResourceManager.GetString("ControlText_ViewStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a post.
        /// </summary>
        internal static string ControlText_Write {
            get {
                return ResourceManager.GetString("ControlText_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=400, user-scalable=no&quot;/&gt;
        ///&lt;title&gt;Untitled 1&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;color: #FFFFFF; background-color: #000000;&quot;&gt;
        ///&lt;p&gt;
        ///GNU GENERAL PUBLIC LICENSE
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Version 2, June 1991
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Copyright (C) 1989, 1991 F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eula {
            get {
                return ResourceManager.GetString("Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There may be a problem with the url that was entered.  Did the url start with http://, or was xmlrpc.php left off the end?  The default for the WordPress.com site, for example, is https://wordpress.com/xmlrpc.php..
        /// </summary>
        internal static string Message_CheckTheUrl {
            get {
                return ResourceManager.GetString("Message_CheckTheUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading statistics....
        /// </summary>
        internal static string Message_DownloadingStatistics {
            get {
                return ResourceManager.GetString("Message_DownloadingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acquiring permalink....
        /// </summary>
        internal static string Messages_AcquiringPermalink {
            get {
                return ResourceManager.GetString("Messages_AcquiringPermalink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approving comment....
        /// </summary>
        internal static string Messages_ApprovingComment {
            get {
                return ResourceManager.GetString("Messages_ApprovingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approving comments....
        /// </summary>
        internal static string Messages_ApprovingComments {
            get {
                return ResourceManager.GetString("Messages_ApprovingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Copied.
        /// </summary>
        internal static string Messages_ContentCopied {
            get {
                return ResourceManager.GetString("Messages_ContentCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creating new category....
        /// </summary>
        internal static string Messages_CreatingNewCategory {
            get {
                return ResourceManager.GetString("Messages_CreatingNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting comment....
        /// </summary>
        internal static string Messages_DeletingComment {
            get {
                return ResourceManager.GetString("Messages_DeletingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting comments....
        /// </summary>
        internal static string Messages_DeletingComments {
            get {
                return ResourceManager.GetString("Messages_DeletingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting page....
        /// </summary>
        internal static string Messages_DeletingPage {
            get {
                return ResourceManager.GetString("Messages_DeletingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleting post....
        /// </summary>
        internal static string Messages_DeletingPost {
            get {
                return ResourceManager.GetString("Messages_DeletingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Messages_Hello {
            get {
                return ResourceManager.GetString("Messages_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Messages_Info {
            get {
                return ResourceManager.GetString("Messages_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid WordPress.com credentials.
        /// </summary>
        internal static string Messages_InvalidCredentials {
            get {
                return ResourceManager.GetString("Messages_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string Messages_Loading {
            get {
                return ResourceManager.GetString("Messages_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in....
        /// </summary>
        internal static string Messages_LoggingIn {
            get {
                return ResourceManager.GetString("Messages_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordPress for Windows Phone is an Open Source app that empowers you to write new posts, edit content, view stats, and manage comments for your WordPress site..
        /// </summary>
        internal static string Messages_MarketDescription {
            get {
                return ResourceManager.GetString("Messages_MarketDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marking comment as spam....
        /// </summary>
        internal static string Messages_MarkingAsSpam {
            get {
                return ResourceManager.GetString("Messages_MarkingAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marking comments as spam....
        /// </summary>
        internal static string Messages_MarkingCommentsAsSpam {
            get {
                return ResourceManager.GetString("Messages_MarkingCommentsAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields.
        /// </summary>
        internal static string Messages_MissingFields {
            get {
                return ResourceManager.GetString("Messages_MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a reply..
        /// </summary>
        internal static string Messages_MissingReply {
            get {
                return ResourceManager.GetString("Messages_MissingReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stats are available for the current query..
        /// </summary>
        internal static string Messages_NoStatsAvailable {
            get {
                return ResourceManager.GetString("Messages_NoStatsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replying to comment....
        /// </summary>
        internal static string Messages_ReplyingToComment {
            get {
                return ResourceManager.GetString("Messages_ReplyingToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving categories....
        /// </summary>
        internal static string Messages_RetrievingCategories {
            get {
                return ResourceManager.GetString("Messages_RetrievingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving comments....
        /// </summary>
        internal static string Messages_RetrievingComments {
            get {
                return ResourceManager.GetString("Messages_RetrievingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving everything....
        /// </summary>
        internal static string Messages_RetrievingEverything {
            get {
                return ResourceManager.GetString("Messages_RetrievingEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving page....
        /// </summary>
        internal static string Messages_RetrievingPage {
            get {
                return ResourceManager.GetString("Messages_RetrievingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving pages....
        /// </summary>
        internal static string Messages_RetrievingPages {
            get {
                return ResourceManager.GetString("Messages_RetrievingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving post....
        /// </summary>
        internal static string Messages_RetrievingPost {
            get {
                return ResourceManager.GetString("Messages_RetrievingPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving posts....
        /// </summary>
        internal static string Messages_RetrievingPosts {
            get {
                return ResourceManager.GetString("Messages_RetrievingPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unapproving comment....
        /// </summary>
        internal static string Messages_UnapprovingComment {
            get {
                return ResourceManager.GetString("Messages_UnapprovingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unapproving comments....
        /// </summary>
        internal static string Messages_UnapprovingComments {
            get {
                return ResourceManager.GetString("Messages_UnapprovingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading changes....
        /// </summary>
        internal static string Messages_UploadingChanges {
            get {
                return ResourceManager.GetString("Messages_UploadingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading media....
        /// </summary>
        internal static string Messages_UploadingMedia {
            get {
                return ResourceManager.GetString("Messages_UploadingMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete page.
        /// </summary>
        internal static string Options_PageActions_DeletePage {
            get {
                return ResourceManager.GetString("Options_PageActions_DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit page.
        /// </summary>
        internal static string Options_PageActions_EditPage {
            get {
                return ResourceManager.GetString("Options_PageActions_EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view comments.
        /// </summary>
        internal static string Options_PageActions_ViewComments {
            get {
                return ResourceManager.GetString("Options_PageActions_ViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view page.
        /// </summary>
        internal static string Options_PageActions_ViewPage {
            get {
                return ResourceManager.GetString("Options_PageActions_ViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete post.
        /// </summary>
        internal static string Options_PostActions_DeletePost {
            get {
                return ResourceManager.GetString("Options_PostActions_DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit post.
        /// </summary>
        internal static string Options_PostActions_EditPost {
            get {
                return ResourceManager.GetString("Options_PostActions_EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view comments.
        /// </summary>
        internal static string Options_PostActions_ViewComments {
            get {
                return ResourceManager.GetString("Options_PostActions_ViewComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view post.
        /// </summary>
        internal static string Options_PostActions_ViewPost {
            get {
                return ResourceManager.GetString("Options_PostActions_ViewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string Options_RefreshEntity_Comments {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everything.
        /// </summary>
        internal static string Options_RefreshEntity_Everything {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        internal static string Options_RefreshEntity_Pages {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posts.
        /// </summary>
        internal static string Options_RefreshEntity_Posts {
            get {
                return ResourceManager.GetString("Options_RefreshEntity_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        internal static string Options_StatisticPeriod_AllTime {
            get {
                return ResourceManager.GetString("Options_StatisticPeriod_AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string Options_StatisticPeriod_LastMonth {
            get {
                return ResourceManager.GetString("Options_StatisticPeriod_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter.
        /// </summary>
        internal static string Options_StatisticPeriod_LastQuarter {
            get {
                return ResourceManager.GetString("Options_StatisticPeriod_LastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string Options_StatisticPeriod_LastWeek {
            get {
                return ResourceManager.GetString("Options_StatisticPeriod_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string Options_StatisticPeriod_LastYear {
            get {
                return ResourceManager.GetString("Options_StatisticPeriod_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicks.
        /// </summary>
        internal static string Options_StatisticType_Clicks {
            get {
                return ResourceManager.GetString("Options_StatisticType_Clicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Views.
        /// </summary>
        internal static string Options_StatisticType_PostViews {
            get {
                return ResourceManager.GetString("Options_StatisticType_PostViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrers.
        /// </summary>
        internal static string Options_StatisticType_Referrers {
            get {
                return ResourceManager.GetString("Options_StatisticType_Referrers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Terms.
        /// </summary>
        internal static string Options_StatisticType_SearchTerms {
            get {
                return ResourceManager.GetString("Options_StatisticType_SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Options_StatisticType_Views {
            get {
                return ResourceManager.GetString("Options_StatisticType_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this comment?.
        /// </summary>
        internal static string Prompt_ConfirmDeleteComment {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} {1}?.
        /// </summary>
        internal static string Prompt_ConfirmDeleteCommentsFormat {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeleteCommentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete page &apos;{0}&apos;?.
        /// </summary>
        internal static string Prompt_ConfirmDeletePageFormat {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeletePageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete post &apos;{0}&apos;?.
        /// </summary>
        internal static string Prompt_ConfirmDeletePostFormat {
            get {
                return ResourceManager.GetString("Prompt_ConfirmDeletePostFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark this comment as spam?.
        /// </summary>
        internal static string Prompt_ConfirmMarkSpamComment {
            get {
                return ResourceManager.GetString("Prompt_ConfirmMarkSpamComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark as spam {0} {1}?.
        /// </summary>
        internal static string Prompt_ConfirmMarkSpamCommentsFormat {
            get {
                return ResourceManager.GetString("Prompt_ConfirmMarkSpamCommentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Actions.
        /// </summary>
        internal static string Prompt_PageActions {
            get {
                return ResourceManager.GetString("Prompt_PageActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Actions.
        /// </summary>
        internal static string Prompt_PostActions {
            get {
                return ResourceManager.GetString("Prompt_PostActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a thumbnail size..
        /// </summary>
        internal static string Prompt_SelectThumbnailSize {
            get {
                return ResourceManager.GetString("Prompt_SelectThumbnailSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Editing.
        /// </summary>
        internal static string Prompts_CancelEditing {
            get {
                return ResourceManager.GetString("Prompts_CancelEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        internal static string Prompts_Comment {
            get {
                return ResourceManager.GetString("Prompts_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string Prompts_Comments {
            get {
                return ResourceManager.GetString("Prompts_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Prompts_Confirm {
            get {
                return ResourceManager.GetString("Prompts_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Upload Error.
        /// </summary>
        internal static string Prompts_MediaError {
            get {
                return ResourceManager.GetString("Prompts_MediaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error was encountered when uploading media.  Would you still like to upload the post?.
        /// </summary>
        internal static string Prompts_MediaErrorContent {
            get {
                return ResourceManager.GetString("Prompts_MediaErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current blog doesn&apos;t have an api key.  Please enter one on the settings page..
        /// </summary>
        internal static string Prompts_MissingApikey {
            get {
                return ResourceManager.GetString("Prompts_MissingApikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a category name..
        /// </summary>
        internal static string Prompts_MissingCategoryName {
            get {
                return ResourceManager.GetString("Prompts_MissingCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string Prompts_MissingPassword {
            get {
                return ResourceManager.GetString("Prompts_MissingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid url..
        /// </summary>
        internal static string Prompts_MissingUrl {
            get {
                return ResourceManager.GetString("Prompts_MissingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name..
        /// </summary>
        internal static string Prompts_MissingUserName {
            get {
                return ResourceManager.GetString("Prompts_MissingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        internal static string Prompts_Page {
            get {
                return ResourceManager.GetString("Prompts_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post.
        /// </summary>
        internal static string Prompts_Post {
            get {
                return ResourceManager.GetString("Prompts_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to refresh?.
        /// </summary>
        internal static string Prompts_RefreshEntity {
            get {
                return ResourceManager.GetString("Prompts_RefreshEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the blog you&apos;d like to delete..
        /// </summary>
        internal static string Prompts_SelectBlogToDelete {
            get {
                return ResourceManager.GetString("Prompts_SelectBlogToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a category..
        /// </summary>
        internal static string Prompts_SelectCategory {
            get {
                return ResourceManager.GetString("Prompts_SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much data would you like to see?.
        /// </summary>
        internal static string Prompts_SelectStatisticPeriod {
            get {
                return ResourceManager.GetString("Prompts_SelectStatisticPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which statistic would you like data for?.
        /// </summary>
        internal static string Prompts_SelectStatisticType {
            get {
                return ResourceManager.GetString("Prompts_SelectStatisticType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the server returned invalid data. Please try again..
        /// </summary>
        internal static string Prompts_ServerReturnedInvalidXmlRpcMessage {
            get {
                return ResourceManager.GetString("Prompts_ServerReturnedInvalidXmlRpcMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel editing this {0}?.
        /// </summary>
        internal static string Prompts_SureCancel {
            get {
                return ResourceManager.GetString("Prompts_SureCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the server returned invalid data. Please try again..
        /// </summary>
        internal static string Prompts_XeElementMissing {
            get {
                return ResourceManager.GetString("Prompts_XeElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the requested action failed. Please try again..
        /// </summary>
        internal static string Prompts_XmlRpcOperationFailed {
            get {
                return ResourceManager.GetString("Prompts_XmlRpcOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actions.
        /// </summary>
        internal static string Title_Actions {
            get {
                return ResourceManager.GetString("Title_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add account.
        /// </summary>
        internal static string Title_AddAccount {
            get {
                return ResourceManager.GetString("Title_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new category.
        /// </summary>
        internal static string Title_AddNewCategory {
            get {
                return ResourceManager.GetString("Title_AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string Title_All {
            get {
                return ResourceManager.GetString("Title_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVED.
        /// </summary>
        internal static string Title_Approve {
            get {
                return ResourceManager.GetString("Title_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blogs.
        /// </summary>
        internal static string Title_Blogs {
            get {
                return ResourceManager.GetString("Title_Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the url valid?.
        /// </summary>
        internal static string Title_CheckTheUrl {
            get {
                return ResourceManager.GetString("Title_CheckTheUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string Title_Comments {
            get {
                return ResourceManager.GetString("Title_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string Title_ConfirmDelete {
            get {
                return ResourceManager.GetString("Title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit page.
        /// </summary>
        internal static string Title_EditPage {
            get {
                return ResourceManager.GetString("Title_EditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit post.
        /// </summary>
        internal static string Title_EditPost {
            get {
                return ResourceManager.GetString("Title_EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate comment.
        /// </summary>
        internal static string Title_ModerateComment {
            get {
                return ResourceManager.GetString("Title_ModerateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate comments.
        /// </summary>
        internal static string Title_ModerateComments {
            get {
                return ResourceManager.GetString("Title_ModerateComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new page.
        /// </summary>
        internal static string Title_NewPage {
            get {
                return ResourceManager.GetString("Title_NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new post.
        /// </summary>
        internal static string Title_NewPost {
            get {
                return ResourceManager.GetString("Title_NewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pages.
        /// </summary>
        internal static string Title_Pages {
            get {
                return ResourceManager.GetString("Title_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to posts.
        /// </summary>
        internal static string Title_Posts {
            get {
                return ResourceManager.GetString("Title_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferences.
        /// </summary>
        internal static string Title_Preferences {
            get {
                return ResourceManager.GetString("Title_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select categories.
        /// </summary>
        internal static string Title_SelectCategories {
            get {
                return ResourceManager.GetString("Title_SelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPAM.
        /// </summary>
        internal static string Title_Spam {
            get {
                return ResourceManager.GetString("Title_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stats.
        /// </summary>
        internal static string Title_Stats {
            get {
                return ResourceManager.GetString("Title_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNAPPROVED.
        /// </summary>
        internal static string Title_Unapprove {
            get {
                return ResourceManager.GetString("Title_Unapprove", resourceCulture);
            }
        }
    }
}
