//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordPress.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XMLRPCTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLRPCTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordPress.Model.XMLRPCTable", typeof(XMLRPCTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;blogger.deletePost&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{0}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{3}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string blogger_deletePost {
            get {
                return ResourceManager.GetString("blogger_deletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;metaWeblog.editPost&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{0}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;mt_keywords&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;string&gt;{3} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metaWeblog_editPost {
            get {
                return ResourceManager.GetString("metaWeblog_editPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;metaWeblog.editPost&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{0}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;mt_keywords&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;string&gt;{3} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metaWeblog_editPost_featuredImage {
            get {
                return ResourceManager.GetString("metaWeblog_editPost_featuredImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;metaWeblog.getPost&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{0}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string metaWeblog_getPost {
            get {
                return ResourceManager.GetString("metaWeblog_getPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;metaWeblog.newPost&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;mt_keywords&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;string&gt;{3}&lt;/string&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metaWeblog_newPost {
            get {
                return ResourceManager.GetString("metaWeblog_newPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;metaWeblog.newPost&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;mt_keywords&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;string&gt;{3}&lt;/string&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metaWeblog_newPost_featuredImage {
            get {
                return ResourceManager.GetString("metaWeblog_newPost_featuredImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;mt.getRecentPostTitles&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{3}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;
        ///.
        /// </summary>
        internal static string mt_getRecentPostTitles {
            get {
                return ResourceManager.GetString("mt_getRecentPostTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.deleteComment&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{3}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string wp_deleteComment {
            get {
                return ResourceManager.GetString("wp_deleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.deletePage&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{3}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string wp_deletePage {
            get {
                return ResourceManager.GetString("wp_deletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.editComment&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{3}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wp_editComment {
            get {
                return ResourceManager.GetString("wp_editComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getCategories&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;
        ///.
        /// </summary>
        internal static string wp_getCategories {
            get {
                return ResourceManager.GetString("wp_getCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getCommentCount&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{3}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string wp_getCommentCount {
            get {
                return ResourceManager.GetString("wp_getCommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getComments&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;post_id&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;string&gt;{3}&lt;/string&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wp_getComments {
            get {
                return ResourceManager.GetString("wp_getComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getMediaItem&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{3}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string wp_getMediaItem {
            get {
                return ResourceManager.GetString("wp_getMediaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getOptions&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;
        ///.
        /// </summary>
        internal static string wp_getOptions {
            get {
                return ResourceManager.GetString("wp_getOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getPageList&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string wp_getPageList {
            get {
                return ResourceManager.GetString("wp_getPageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getPostFormats&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;show-supported&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;boolean&gt;1&lt;/boole [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wp_getPostFormats {
            get {
                return ResourceManager.GetString("wp_getPostFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.getUsersBlogs&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{0}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///  &lt;/params&gt;
        ///&lt;/methodCall&gt;.
        /// </summary>
        internal static string wp_getUsersBlogs {
            get {
                return ResourceManager.GetString("wp_getUsersBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.newCategory&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;description&lt;/name&gt;
        ///            &lt;value&gt;
        ///              &lt;string&gt;{3}&lt;/string&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wp_newCategory {
            get {
                return ResourceManager.GetString("wp_newCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.newComment&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{0}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;i4&gt;{3}&lt;/i4&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wp_newComment {
            get {
                return ResourceManager.GetString("wp_newComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;methodCall&gt;
        ///  &lt;methodName&gt;wp.uploadFile&lt;/methodName&gt;
        ///  &lt;params&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;int&gt;{0}&lt;/int&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{1}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;value&gt;
        ///        &lt;string&gt;{2}&lt;/string&gt;
        ///      &lt;/value&gt;
        ///    &lt;/param&gt;
        ///    &lt;param&gt;
        ///      &lt;struct&gt;
        ///        &lt;member&gt;
        ///          &lt;name&gt;name&lt;/name&gt;
        ///          &lt;value&gt;
        ///            &lt;string&gt;{3}&lt;/string&gt;
        ///          &lt;/value&gt;
        ///        &lt;/memb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wp_uploadFile {
            get {
                return ResourceManager.GetString("wp_uploadFile", resourceCulture);
            }
        }
    }
}
